### PR TITLE
Java 10

### LINKED ISSUE #3: Upgrade to Java 10?
@beevelop

### PR DESCRIPTION
**Pull request by pedrofurtado**
@beevelop 

Closes #3

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@beevelop Is this PR ready for merge? I can make the required changes, if necessary 👍

**Comment by pedrofurtado** [comment]
@beevelop Is this PR ready for merge? I can make the required changes, if necessary 👍

**Comment by beevelop** [comment]
Thank you for the contribution. We have to check all the other images for compatibility prior to merging this. Unfortunately it's not only the Ionic image, that uses this image as the basis. I'll try to deal with it this weekend 👍

**Comment by pedrofurtado** [comment]
@beevelop No problems! Anyway, I can help you with something, if necessary :+1:

**Comment by Phoscur** [comment]
Android still requires Java 8

**Pull request closed without merging**
